# Generated by Django 5.0.1 on 2024-01-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('TableID', models.AutoField(primary_key=True, serialize=False)),
                ('TableNishima', models.IntegerField()),
                ('TableSajit', models.IntegerField()),
                ('TableTotal', models.IntegerField()),
            ],
        ),
    ]
