# Generated by Django 5.0.1 on 2024-01-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_remove_table_tabletotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='TableID',
            new_name='TableId',
        ),
        migrations.AddField(
            model_name='table',
            name='TableTotal',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='TableNishima',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='TableSajit',
            field=models.FloatField(),
        ),
    ]
