# Generated by Django 5.0.1 on 2024-01-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0003_rename_tableid_table_tableid_table_tabletotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='TableNishima',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='TableSajit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='TableTotal',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
