# Generated by Django 5.0.1 on 2024-01-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0004_alter_table_tablenishima_alter_table_tablesajit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='TableId',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='TableNishima',
            new_name='SubjectA',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='TableSajit',
            new_name='SubjectB',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='TableTotal',
            new_name='Total',
        ),
    ]
