# Generated by Django 5.0.1 on 2024-01-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0005_rename_tableid_table_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Average',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
